##Setup environment for Daily_Rainfall_Over_NSW
##conda env create -f environment.yaml

name: 'daily-rainfall-group4'
channels:
  - conda-forge
  - defaults
  - plotly
dependencies:
  - ipykernel
  - ipython>=7.15
  - scipy
  - pandas
  - numpy
  - plotly
  - matplotlib
  - pip
  - requests
  - pip:
    - pyarrow
    - rpy2_arrow